- include/nana/paint/detail/image_bmp.hpp
- source/gui/layout_utility.cpp
This fixes the following errors and warnings:
```
ryan@DevPC-LX:~/stuff/nana/build/makefile$ make -B GCC=clang++
...
clang++ -g -c ../../source/gui/layout_utility.cpp -o ../../source/gui/layout_utility.o -I../../include -I/usr/include/freetype2 -std=c++0x -Wall
../../source/gui/layout_utility.cpp:21:19: error: expected '(' for
function-style cast or type construction
if (r1.y + long long(r1.height) <= r2.y) return false;
~~~~ ^
../../source/gui/layout_utility.cpp:22:26: error: expected '(' for
function-style cast or type construction
if(r1.y >= r2.y + long long(r2.height)) return false;
~~~~ ^
../../source/gui/layout_utility.cpp:24:18: error: expected '(' for
function-style cast or type construction
if(r1.x + long long(r1.width) <= r2.x) return false;
~~~~ ^ …
```
> Fix Linux builds (again)

- include/nana/gui/widgets/button.hpp
- include/nana/gui/widgets/categorize.hpp
- include/nana/gui/widgets/checkbox.hpp
- include/nana/gui/widgets/combox.hpp
- include/nana/gui/widgets/date_chooser.hpp
- include/nana/gui/widgets/float_listbox.hpp
- include/nana/gui/widgets/form.hpp
- include/nana/gui/widgets/frame.hpp
- include/nana/gui/widgets/label.hpp
- include/nana/gui/widgets/listbox.hpp
- include/nana/gui/widgets/menu.hpp
- include/nana/gui/widgets/panel.hpp
- include/nana/gui/widgets/picture.hpp
- include/nana/gui/widgets/progress.hpp
- include/nana/gui/widgets/scroll.hpp
- include/nana/gui/widgets/slider.hpp
- include/nana/gui/widgets/spinbox.hpp
- include/nana/gui/widgets/tabbar.hpp
- include/nana/gui/widgets/textbox.hpp
- include/nana/gui/widgets/toolbar.hpp
- include/nana/gui/widgets/treebox.hpp
- include/nana/gui/widgets/widget.hpp
- source/gui/place.cpp
I´m not sure, but It seems that the new leaft_left_ size is calculated by scaling the previous value. But if the first size was 0, no matter how big the scale is, it will be 0 always.
> doxy-comments and place-split avoiding 0 left size

- include/nana/gui/widgets/panel.hpp
- source/gui/widgets/label.cpp
with this fix I can make this:
[Compare with this](https://github.com/qPCR4vir/nana-demo/issues/1)
I also updated : https://github.com/qPCR4vir/nana-demo/blob/master/Examples/a_group_impl.cpp
> fix: make panel and label have the same bgcolor as the owner

- source/gui/widgets/skeletons/text_editor.cpp
Hi,
I have:
```cpp
_textBox.set_highlight("place_keywords", nana::colors::blue, nana::colors::white);
_textBox.set_keywords ("place_keywords", true,true, { "arrange", "collapse", "gap", "grid", 
"margin", "min", "max", "repeated", "variable", "vertical", "vert", "weight", "horizontal" });
_textBox.set_highlight("place_simbols", nana::colors::blue, nana::colors::yellow);
_textBox.set_keywords ("place_simbols", true,false, {"<",">", "|", "%", "[","]" });
```
First picture, the problem, secound, the fix.
> FIX: find only first keyword in line

- include/nana/gui/widgets/panel.hpp
small change to make nana compile with mingw again.
best regards, jan
^
> fixing lookup error from gcc/mingw

- .gitignore
- CMakeLists.txt
- README.md
- biicode.conf
- include/nana/config.hpp
- include/nana/deploy.hpp
- include/nana/std_condition_variable.hpp
- include/nana/std_mutex.hpp
- include/nana/std_thread.hpp
- source/deploy.cpp
1. Add Biicode example in README
2. Eliminate macro redefinition warnings when used with Biicode. When used with Biicode, the default config.hpp will be used which will automatically detect its environment. When used individually(via raw CMake), nothing changes.
> modify readme and detect environment for biicode automatically

- source/gui/widgets/menubar.cpp
I modified below code to match with standard menu behaviours.
File : source/gui/widgets/menubar.cpp
Method : nana::drawerbase::menubar::trigger::key_press
Below are the summary of changes.
* Pressing unknown (non shortcut) key does not close opened menu. (previously, doing so closes menu but standard menu does not.)
* If a menubar is focused (receives keyboard input), pressing os_arrow_up & os_arrow_down & enter keys opens a menu. (previously, pressing those keys does not open a menu)
* Pressing menu shortcut key opens a menu in a modal form.  (somehow nana::drawerbase::menubar::trigger::shortkey is not called with modal dialog, so I add a workaround in key_press method)
> Menubar key_press handling improvements

- source/gui/detail/win32/bedrock.cpp
I modified below code so that pressing Shift+Tab keys changes control focus to previous tabstop.
File : source\gui\detail\win32\bedrock.cpp
Func : nana::detail::Bedrock_WIN32_WindowProc
```c+++
// case WM_KEYDOWN:
auto the_next = brock.wd_manager.tabstop(msgwnd, (::GetKeyState(VK_SHIFT) >= 0));
```
https://msdn.microsoft.com/en-us/library/windows/desktop/dn742465
> Pressing Shift+Tab moves input focus to the previous control.

- include/nana/gui/widgets/listbox.hpp
Here is an excerpt from output window of VS2013.
1>c:\libs\nana\include\nana\gui\widgets\listbox.hpp(251): warning C4018: '<' : signed/unsigned mismatch (..\form_do_you_even_lift.cpp)
1>          c:\projects\bro\form_do_you_even_lift.cpp(646) : see reference to function template instantiation 'nana::drawerbase::listbox::item_proxy &nana::drawerbase::listbox::item_proxy::resolve_from<Data>(const T &)' being compiled
1>          with
1>          [
1>              T=Data
1>          ]
> trivial fix for compiler warning

- include/nana/datetime.hpp
- include/nana/deploy.hpp
- source/charset.cpp
- source/datetime.cpp
- source/detail/win32/platform_spec.cpp
Hi, I edited nana's code a little bit to remove some warnings with VS2013.
And in time::time(unsigned hour, unsigned minute, unsigned second) constructor, I added return statement if args are valid.
> remove some warnings with VS2013

- include/nana/gui/widgets/progress.hpp
- source/gui/widgets/progress.cpp
I was working with FreeMe and I realized that a common situation of stopping an action for with we use a progressbar is to communicate that state using self the progressbar.
It can be more sophisticate, but now is working. See the FreeMe (search for "stop" there):
https://github.com/qPCR4vir/nana-demo/blob/file_explorer/FreeMe.cpp
Maybe we could throw in inc() if the progress is stopped?
> progressbar with stop()

- include/nana/gui/detail/native_window_interface.hpp
- include/nana/gui/detail/widget_notifier_interface.hpp
- include/nana/gui/detail/window_manager.hpp
- include/nana/gui/programming_interface.hpp
- include/nana/gui/widgets/label.hpp
- include/nana/gui/widgets/skeletons/text_editor.hpp
- include/nana/paint/detail/image_bmp.hpp
- include/nana/paint/detail/image_ico.hpp
- include/nana/paint/detail/image_impl_interface.hpp
- include/nana/paint/graphics.hpp
- include/nana/paint/image.hpp
- source/gui/detail/native_window_interface.cpp
- source/gui/detail/win32/bedrock.cpp
- source/gui/detail/window_manager.cpp
- source/gui/filebox.cpp
- source/gui/programming_interface.cpp
- source/gui/widgets/combox.cpp
- source/gui/widgets/label.cpp
- source/gui/widgets/skeletons/text_editor.cpp
- source/gui/widgets/spinbox.cpp
- source/gui/widgets/textbox.cpp
- source/paint/graphics.cpp
- source/paint/image.cpp
Hi, I've added several features to nana library.
- added OFN_NOCHANGEDIR flag to OPENFILENAME::Flags in nana::filebox::show
- Big & Small icon support for Windows.
- On Windows, the system displays the large icon in the ALT+TAB dialog box, and the small icon in the window caption.
- Open icon image from memory feature.
- nana::paint::image::open_icon method seems a bit too concrete.
- I've added this feature to set icon image from memory that is retrieved from resource data within executable file.
- Label::relate method.
- It works like HTML label element **for** attribute.
- By clicking a label, specified widget will be focused.
- Textbox selection handling improvements.
- Select textbox content after tabstop event.
- When textbox is not focused, its selection is not drawn to make it …
> Several modifications

- source/paint/detail/native_paint_interface.cpp
Which was causing a wrong deletion of the array
> Fix missing array declaration in a unique_ptr

- source/filesystem/filesystem.cpp
a small fix for the mingw users of us
another solution is to just write
return static_cast<nana::string>(buf);
i'm not sure which one is better, so i stayed with the one 3 lines above
> small fix for gcc/mingw

- build/vc2015/nana.vcxproj
To avoid excessive recompilation after each change in configuration and conflicts during linking.
It allows simple selection of configuration inside the IDE.
This is optional, just convenience.
> return configuration specific names

- include/nana/gui/widgets/listbox.hpp
- source/gui/widgets/listbox.cpp
When calling templated append() overload on a shown listbox, auto_draw
caused an early redraw, which issued the inline widget set() member
function before the value() and value_ptr() were actually set.
> Fix listbox for auto_draw+inline_factory+item_proxy::value.

- CMakeLists.txt
- source/charset.cpp
here are three little fixes for the current 1.3 alpha release.
hope the commits are self-explanatory. if not pls give me ring.
1. Changed CMakeLists.txt encoding to utf-8 (i simply suppose thats how it should be)
2. CMake 3.3.0 told me there was a problem with 'if' --> see the change 
3. seems like in Microsofts STL already includes ```<cstring>``` at some point, but with libstdc++ it was required to include it explicitly
there is another issue i could not fix:
using Microsofts STL it is possible to open a std::basic_ifstream<char> with an wchar_t* path (even though it's not standard behaviour)
```
Error:
In file included from D:\nana\source\paint\image.cpp:31:0:
D:\nana\source\paint\detail/image_bmp.hpp: In member function 'virtual bool nana::paint::detail::image_bmp::open(const …
```
> Fix for mingw users (incomplete)

- source/gui/widgets/menu.cpp
Stretch menu image (icons) only when don't fit, center it otherwise.
> Fix for menu images

- include/nana/gui/widgets/toolbar.hpp
- source/gui/widgets/toolbar.cpp
This patch has 2 new features:
1- new option at constructor to enable creation of detached toolbar from his parent, this enable the use of toolbar anywhere and the size can be controlled by a layout manager.
2- add a new option in order to enable to place buttons at right part, the widget has a new method go_right() after calling it, every new button is right aligned.
Both changes don't break compatibility with old code.
I attach an example in order to appreciate this change.
> Toolbar improvement.

- .gitignore
- .travis.yml
- CMakeLists.txt
- include/nana/config.hpp
- include/nana/gui/detail/bedrock.hpp
- include/nana/gui/programming_interface.hpp
- include/nana/gui/wvl.hpp
- source/gui/detail/bedrock_windows.cpp
- source/gui/programming_interface.cpp
- source/gui/wvl.cpp
[It is working good](https://travis-ci.org/qPCR4vir/nana/jobs/113431787).
We need to set this automatically in cmake. But first we need a general way to exit from an application from the parallel GUI testing function. Now I use `fm.close()`, and I need to pass a pointer to the main form to that function to do that. A general `API::exit()` will be much better but don't works. Why? With `API::exit()` nana can add a default GUI test to any program when compiled with that option, with is ideal for travis.  
Also, some demos compiled [but don't pass the run test](https://travis-ci.org/qPCR4vir/nana/jobs/113411795) - the list is at the end of `.travis.yml`. We need to fix that. It maybe a problem with [the Xvfb, an X server to emulate display](http://www.xfree86.org/4.0.1/Xvfb.1.html)? See hier …
> Automatic GUI test pass in travis

- source/paint/image.cpp
Hi, this PR adds a feature to load icon image data to image::open method on Windows platform.
I also changed image_ico::open method so that it uses CreateIconFromResourceEx WindowsAPI
instead of CreateIconFromResource. The reason is CreateIconFromResource makes loaded icon image blurry.
I checked issues #133 but loading icon image from exe file feature in nana::paint::create_image function is not adequate since I intend to use multiple icons from exe file resouce data.
By the way, I use below code to load resouce icons on Windows application.
```
void* load_icon_res(HMODULE hModule, int id, DWORD& dwResourceSize, int cxDesired, int cyDesired)
{
auto hResource		= FindResource(hModule, MAKEINTRESOURCE(id), RT_GROUP_ICON);	if (!hResource) { return nullptr; }
dwResourceSize		= …
```
> a feature to load icon image data to image::open method

- include/nana/c++defines.hpp
-  Recent versions of clang have support for make_unique.
- Check if macro "__cpp_lib_experimental_filesystem" is defined and match with the standard value.
> c++ defines patch

- source/gui/widgets/menu.cpp
Used same behavior for the splitter.
> Fixed behavior of disabled items in the menus when scrolling with arrow keys.

- source/paint/detail/image_png.hpp
Compilation was failing with the "enable png" flag. This was happening
because the memcpy function was being called without the inclusion of
cstring, which declares it. This fixes it.
> Include cstring header on image_png.hpp

- CMakeLists.txt
When using nana as a submodule, this will automatically add the include directories from nana to all targets depending on nana.
Basically this removes the need to add something like
`
target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/external/nana/include)`
to the CMakeLists file of a project using nana
> Use target_include_directories to propagate includes

- include/nana/gui/programming_interface.hpp
`nana\src\nana\include\nana\gui\programming_interface.hpp` line 291 has a non-unicode apostrophe. This creates a large number of warnings (also there is typo).
Related: https://github.com/Microsoft/vcpkg/issues/688
> Fix non-unicode char (and typo)

- include/nana/verbose_preprocessor.hpp
In `nana\verbose_preprocessor.hpp` there is a STRING2 macro to convert macro values to string. 
However, this emits a warning when the latter macro is defined but has no value. For example: 
```
#define STRING2(x) #x
#define SHOW_VALUE(x) " " #x "  =  " STRING2(x) 
SHOW_VALUE(NANA_WINDOWS)
```
This emits C4003 because NANA_WINDOWS is defined but has no value. 
Also applies to _UNICODE and UNICODE (also in `nana\verbose_preprocessor.hpp`)
```
E:\workspace\vcpkgspace\buildtrees\nana\src\nana\include\nana/verbose_preprocessor.hpp(45): warning C4003: not enough actual parameters for macro 'STRING2' (compiling source file E:\workspace\vcpkgspace\buildtrees\nana\src\nana\source\deploy.cpp) [E:\workspace\vcpkgspace\buildtrees\nana\x86-windows-test-rel\nana.vcxproj] …
```
> Fix STRING2 macro to handle defined macros with no value

- build/vc2017/nana.vcxproj
For some reason win32 configuration was broken. There were no include paths and other stuff were just set to their defaults.
> Fix VS2017 project win32 config

- CMakeLists.txt
This turns `NANA_LINKS` variable to a list, thus allowing CMake/MSVC build with dependencies (png, jpeg) enabled.
MSVC does not really understand `-l<name>` flags and concatenating `${<NAME>_LIBRARIES}` into a giant string breaks CMake's metadata passed in that variables.
> CMake: fix NANA_LINKS for MSVC

- include/nana/gui/detail/native_window_interface.hpp
compiler didn't understand std::function
included ```<functional>``` as a fix
> Fixed build error

- include/nana/c++defines.hpp
included algorithm in c++defines.hpp
this fixes std::clamp's feature test which was not working.
__cpp_lib_clamp is defined inside ```<algorithm>```.
Not include ```<algorithm>``` before the feature test introduced the problem.
> Fixed stdc++.hpp build error on gcc 7

- include/nana/gui/widgets/skeletons/text_editor.hpp
- include/nana/gui/widgets/textbox.hpp
- source/gui/widgets/skeletons/text_editor.cpp
- source/gui/widgets/textbox.cpp
- the word under cursor is selected with double-click now
- tested in both editable and read-only modes
This addresses #226.
> Added Windows-style mouse double-click to the textbox

- include/nana/gui/msgbox.hpp
- source/gui/msgbox.cpp
V1.5.4 increased the default minimum width of the entry fields in inputbox to a sensible value of 100 pixels.  However, we sometimes need even wider fields  than this, but it would be weird to make the default any wider than 100 pixels.  This add a setter to increase the width when needed.
> Inputbox set minimum width entry field

- include/nana/std_mutex.hpp
- include/nana/std_thread.hpp
NANA_CMAKE_ENABLE_MINGW_STD_THREADS_WITH_MEGANZ option must still be enabled but mingw.thread.h and mingw.mutex.h will be ignored if _GLIBCXX_HAS_GTHREADS is defined
> use std::thread if gcc is compiled with c++11 threading support

- CMakeLists.txt
add NANA_CMAKE_SHARED_LIB option
if `dlltool` is found `mingw` will also generate the `def` and `lib` files needed by msvc linkers to link with the dll.
`make install` will install the `dll` inside the bin folder (widows).
for linux the `so` will be inside the `lib` directory.
> add cmake option for dynamic linking

- .travis.yml
- CMakeLists.txt
- include/nana/filesystem/filesystem.hpp
- include/nana/stdc++.hpp
- source/filesystem/filesystem.cpp
- source/gui/filebox.cpp
- source/gui/wvl.cpp
see qPCR4vir/nana-demo#13 for related nana-demo changes, without them travis build is always going to fail on tests.
Travis build succeeded with this PR and changes to nana-demo applied:
https://travis-ci.org/pavelxdd/nana/builds/308570743
CMakeLists.txt:
---------------------------
Until now build with boost::filesystem was completely broken,
since cmake exported definitions with wrong name prefixes, and
nana always defaulted to internal filesystem implementation.
After fixing the boost definitions, a number of errors came up
due to incompatibility of boost::filesystem with nana and std
filesystems. This commit tries to fix them all.
filesystem.cpp, filesystem.hpp, filebox.cpp:
--------------------------------------------
boost::filesystem doesn't have a file_time_type, so declared
it in …
> fix compilation with boost::filesystem

- include/nana/filesystem/filesystem.hpp
- include/nana/filesystem/filesystem_ext.hpp
Or just merge your develop or hotfix back to develop-c++17.
> develop-c++17: Fix travis test/demos with gcc 4.9 and boost 1.54

- include/nana/c++defines.hpp
Related to https://github.com/cnjinhao/nana/issues/295, see the detailed description in the issue.
Further investigation revealed that unless the MinGW binary is built with `--enable-threads=posix` - which is not the default - it can't implement threading as we expect in Nana, despite the `mutex` header being present.
I tested the changes with **i686-w64-mingw32-g++**, gcc version 6.3.0 20170516 (GCC), targeting Windows x86 from Linux.
> Checking whether MinGW really supports threads

- source/gui/filebox.cpp
filebox.init_file() is not working on WIN.
This is a possible solution (at least works for me)
Ciao
> fix filebox.init_file()

- CMakeLists.txt
Specifically, making Nana C++ in Fefora 27 will complain about missing <ft2build.h>, and so will Solus.
The following distros have been tested against the change:
Arch Linux, Manjaro, Ubuntu, Fedora, Solus
> Make more Linux distros happy

- include/nana/gui/widgets/textbox.hpp
- source/gui/widgets/textbox.cpp
I've added two new overloads for `textbox::getline`:
```cpp
std::optional<std::string> textbox::getline(std::size_t pos) const;
std::optional<std::string> textbox::getline(std::size_t line_index, std::size_t offset) const;
```
Using `std::optional` the user can have as a result either the string or a failure (the empty state) without need to create a new `std::string` to pass by reference.
> New textbox::getline overload returning an optional<string>

- include/nana/gui/widgets/group.hpp
- source/gui/widgets/group.cpp
The group widget has a method to get the checked status an option in the group.  However, there is no method to set the checked status.  This is needed when an application starts up so that it can set default values, or values from an pre-existing database that is to be edited.
> Add method to check option in group

- source/gui/widgets/button.cpp
Now passing an empty image to button.icon() the previous image is erased from button
> updated button.icon

- source/gui/widgets/treebox.cpp
this avoid inconsistent drawing or too much redrawing. I had trouble trying to sincronize a tree and a list.
```
_tree.events().selected ( [&]( const nana::arg_treebox &tbox_arg_info ) 
{ if (tbox_arg_info.operated) RefreshList(tbox_arg_info.item); });
_tree.events().checked  ( [&]( const nana::arg_treebox &tbox_arg_info )
{                                              
tbox_arg_info.item.value<CMultSec*>()->Selected(tbox_arg_info.operated);
if (tbox_arg_info.item== _tree.selected())  
RefreshList(tbox_arg_info.item);          
});
```
> emit ( tree node selected ) only after mouse_down and checked

- source/gui/element.cpp
- source/gui/widgets/checkbox.cpp
- source/gui/widgets/skeletons/text_editor.cpp
disabled checkbox square now looks like disabled textbox
In addition found an unused instruction in text_editor.cpp: could be replaced or removed (or left as it is :) )
> fix disabled checkbox square

- include/nana/gui/filebox.hpp
- source/gui/filebox.cpp
Hi, this PR adds the feature mentioned in #341.
There can be many decisions when implementing multiple file selection feature such as,
- how to hold multiple filenames internally.
- should `files` method return only filenames? or fullpaths?
I only added support for Windows platform so it makes this feature kinda half-baked...
> Allow multiple file selection with nana::filebox on Windows platform

- .gitattributes
- build/vc2017/nana.vcxproj
Added the file to specify line endings for Visual Studio solutions and projects files. Originally the line endings were `lf` but when Visual Studio updates the files, the application updates the line endings to `crlf`. Some git users use `core.autocrlf true` setting but actually that's not problem-free.
Not all Windows developers install specific version of Windows SDK (it was set to `10.0.14393.0`) so I specified `<inherit from parent or project defaults>` that resulted in `8.1` in my case.
Set project property Multi-processor Compilation to `Yes (/MP)` to shorten build time. I did the same thing in the past (#29) but somehow it's been nullified for some reason.
> Some changes for Visual Studio project files

- source/gui/widgets/skeletons/text_editor.cpp
Hi, this PR fixes `text_editor` class's Ctrl + End key handling.
Tested with `nana-demo`'s `notepad.cpp` example program.
Below are the procedures to reproduce the problem.
- Set focus to `text_editor` widget.
- Add a line by pressing Enter key.
- Press Ctrl + End key.
> Fix ctrl + end key handling with text editor class

- source/gui/filebox.cpp
When the user types in the name of a nonexistent file, or selects a file and then changes the folder, the OFN_FILEMUSTEXIST flag causes the dialog box to pop up a warning message box when the user clicks the "Open" button, instead of closing and returning a nonexistent path.
> OFN_FILEMUSTEXIST for filebox in open mode (Windows)

- include/nana/gui/timer.hpp
* Now is possible to construct a timer with an `unsigned int` or any `std::chrono::duration` like `std::chrono::milliseconds`.
* Added an overload `timer::interval(Duration)` compatible with chrono types:
```cpp
my_timer.interval(std::chrono::milliseconds{25});
my_timer.interval(5s);
```
* Added a templated overload `timer::interval<Duration>()` to get directly chrono types:
```cpp
auto interval = my_timer.interval<std::chrono::microseconds>();
```
I've added the constructor with `unsigned` for consistency with the `interval` function, which accepts an `unsigned int` too, but maybe it would be better to remove all the `unsigned` functions (they are ambiguous about the time unit)?
> timer compatible with std::chrono

- include/nana/gui/timer.hpp
- source/gui/timer.cpp
Deprecated use of `unsigned` overloadings for `timer::timer` and `timer::interval`: as mentioned in #416 `std::chrono::duration`s should be preferred over `unsigned int`s to represent time intervals.
I preferred to deprecate the features instead of removing them (as proposed in #416) as this would have led to breaking changes.
(I didn't have deprecated `unsigned timer::interval() const`; I can do it if needed)
> deprecated use of unsigned overloadings for functions in class timer

- include/nana/gui/widgets/toolbar.hpp
- source/gui/widgets/toolbar.cpp
I've worked a bit on the toolbar widget.
The main addition are toggle button (with group management).
A toggle button can assume 2 different state: not pushed (default) or pushed. Clicking on a toggle button it change from not pushed to pushed and viceversa.
A toggle button can be added to a group. These are the group rules:
1. inside a group only one item at the time is pushed
2. inside a group one item must always be pushed
3. a group with only one item IS NOT a group
Following functions/methods have been add both to toolbar and item_proxy:
bool istoggle() const; ///< Returns true if the tool style is toggle.
bool toggle() const; ///< Gets the tool toggle state (only if tool style is toggle).
item_proxy& toggle(bool toggle_state); ///< Sets the tool toggle state (only if tool style is …
> toolbar : added toggle button

- CMakeLists.txt
- build/cmake/select_filesystem.cmake
- build/cmake/shared_libs.cmake
This prevent the need to copy some dll with some MinGW distribution.
Tested with gcc 9.1.1, the lastest optionfrom https://gcc-mcf.lhmouse.com/
It set: CMAKE_CXX_COMPILER_VERSION = 9.1.1 !!!
I changed the build/cmake/compilers.cmake to add static c++ runtime linking but still need to copy mcfgthread-12.dll with the .exe files.
How to fix that? I want all static linked, and move around just my .exe file
> c++ runtime static linking

- CMakeLists.txt
This commit adds the alias to allow the use of nana::nana in other projects as per guideline https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1#using-a-library-defined-in-the-same-cmake-tree-should-look-the-same-as-using-an-external-library.
This change should not break anything, it only adds an alternative name
> add alias nana::nana in CMakeLists.txt

- source/gui/widgets/listbox.cpp
Items don't always deselect correctly during the `mouse_down` event, because a display position is searched for in a set of absolute positions.
To test the effect this has, run the code below, and click the items "fourth absolute" and "second absolute" in that order.
````
#include <nana/gui.hpp>
#include <nana/gui/widgets/listbox.hpp>
int main()
{
nana::form fm{nana::API::make_center(234, 234)};
fm.div("vert margin=15 <listbox>");
nana::listbox lb{fm};
fm["listbox"] << lb;
lb.append_header("Col 0");
lb.at(0).append("first absolute");
lb.at(0).append("second absolute");
lb.at(0).append("third absolute");
lb.at(0).append("fourth absolute");
lb.at(0).append("fifth absolute");
lb.column_at(0).fit_content();
lb.sort_col(0);
fm.collocate();
fm.show();
nana::exec();
}
````
> fixed another listbox selection bug

- source/gui/place_parts.hpp
Now closing a dockpane when the x button is inside the place area don't show the dock indicator anymore.
> Fixed issue on dockpane close

- build/vc2019/nana.sln
- build/vc2019/nana.vcxproj
- build/vc2019/nana.vcxproj.filters
I added project files for vc2019(sln, vcxproj, vcxproj.filters)
1. Copy to vc2019 from vc2017.
2. Open in vs2019 and migrate to v142.
3. Build all projects configuration with no errors.
> Add project script files for vc2019

- include/nana/gui/detail/drawer.hpp
- include/nana/gui/detail/event_code.hpp
- include/nana/gui/detail/general_events.hpp
- include/nana/gui/widgets/combox.hpp
- include/nana/gui/widgets/skeletons/text_editor.hpp
- include/nana/gui/widgets/spinbox.hpp
- include/nana/gui/widgets/textbox.hpp
- source/gui/detail/bedrock_windows.cpp
- source/gui/detail/drawer.cpp
- source/gui/widgets/combox.cpp
- source/gui/widgets/skeletons/text_editor.cpp
- source/gui/widgets/spinbox.cpp
- source/gui/widgets/textbox.cpp
Because Hangul is a combination character, WM_IME_STARTCOMPOSITION is only called once when the IME input is started, so the position of the composition window is strange.
Therefore, I solved the problem by controlling the state of characters combined using WM_IME_COMPOSITION and WM_IME_CHAR.
We have also improved to support other IME languages such as Chinese and Japanese.
> fix the strange behavior of Korean ime composition window.

- .travis.yml
- build/cmake/install_nana.cmake
- include/nana/gui/detail/widget_geometrics.hpp
- include/nana/gui/msgbox.hpp
- include/nana/gui/widgets/widget.hpp
- source/gui/msgbox.cpp
- source/gui/widgets/progress.cpp
from https://cmake.org/cmake/help/v3.0/command/target_include_directories.html
> Include directories usage requirements commonly differ between the build-tree and the install-tree. The BUILD_INTERFACE and INSTALL_INTERFACE generator expressions can be used to describe separate usage requirements based on the usage location. Relative paths are allowed within the INSTALL_INTERFACE expression and are interpreted relative to the installation prefix. For example:
```
target_include_directories(mylib PUBLIC
$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/mylib>
$<INSTALL_INTERFACE:include/mylib>  # <prefix>/include/mylib
)
```
> FIX 4. inputbox buttons overlaid, missed included in installed nana and both travis and appveyor IC

- build/cmake/shared_libs.cmake
Note: I'm not sure whether this default is the right choice (most projects I have seen used dynamic by default) but at least this commit gives a choice to do otherwise.
I'm not even sure if such thing should be in the CMake scripts at all - perhaps we should do nothing in regards to standard libraries and let everyone use their compiler's default or global CMake settings.
> added option to link C++ standard library statically

- build/cmake/shared_libs.cmake
#469 is broken: don't link statically all lib.
Now tested OK using cmake/mingw-w64-gcc-mcf_20190705_9.1.1_x86/windows10
(still need to "install" mcfgthread-12.dll, but only that one)
> FIX reversion in static linking introduced in #469

- source/charset.cpp
I noticed that `form.icon()` did not work properly under MinGW - long story short, turns out that the [WideCharToMultiByte](https://docs.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-widechartomultibyte) call got an incorrect `cbMultiByte` parameter - thus returned an `ERROR_INSUFFICIENT_BUFFER` error.
- `mbstr.resize(bytes - 1);` is correct - that is counted *without* the terminating zero.
- `cbMultiByte`, however is _"Size, in bytes, of the buffer indicated by lpMultiByteStr."_ so the terminating zero must be counted too.
I am not sure how to proceed with adding checks for all return values of all of the `Stringapiset.h` calls here, so I'll leave that for later. Ideally `wc2mb` should have failed though.
> Fixing incorrect buffer in WideCharToMultiByte call in wc2mb (charset.cpp)

- include/nana/any.hpp
- source/gui/widgets/listbox.cpp
- source/gui/widgets/treebox.cpp
- `treebox.cpp`:  fixed a bug in `trigger::dbl_click()`
`impl_->set_expanded()` was called unconditionally, even if the node had no children. This caused the node icon to change to the "expanded" icon if the node had an icon scheme, even when the node didn't have children.
- `listbox.cpp`:  `listbox::sort_col` doesn't update view
Calling `listbox::sort_col` to change the sort column doesn't update the viewport to reflect the change, forcing the user to call `API::refresh_window` or otherwise perform stupid tricks to force the listbox to refresh.
- `any.hpp`: argument not forwarded
A constructor and an overload of the assignment operator each have a forwarding reference as a parameter, but they don't actually forward the argument.
- `treebox.cpp`:  fixed buggy `item_proxy` postfix …
> Bug fixes for listbox, treebox, and nana::any

- source/gui/widgets/tabbar.cpp
When a tab is deleted using `tabbar::erase`, `trigger::erase` is called. This function does not call `API::refresh_window` if the tab was erased successfully (unlike `trigger::tab_color`, `trigger::tab_image`, etc.), thus the tab is still visible until an interaction is made (like mouse click on `tabbar`).
> Fix tabbar drawing not updated when a tab is erased

- build/cmake/shared_libs.cmake
The OR syntax doesn't work.
```
[100%] Linking CXX shared library libnana.so
c++: error: $<$<OR:$: No such file or directory
c++: error: unrecognized command line option ‘-static-libstdc++>’; did you mean ‘-static-libstdc++’?
CMakeFiles/nana.dir/build.make:1260: recipe for target 'libnana.so' failed
make[2]: *** [libnana.so] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/nana.dir/all' failed
make[1]: *** [CMakeFiles/nana.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
Only one COMPILER_ID can be true at any one time. The rest will evaluate to nothing.
> fix static stdlib generator expression

- include/nana/gui/widgets/detail/tree_cont.hpp
- include/nana/gui/widgets/treebox.hpp
- source/gui/widgets/treebox.cpp
Treebox items can be hidden and shown. It is useful feature for filtering or searching on large treeboxes, as it's now possible to work with the part of the treebox without actually removing any items.
Implementation mostly inspired by the implementation of the "expanded" property.
> treebox - allow treebox node to be hidden

- source/gui/widgets/menu.cpp
When the user opens a submenu containing items with the style `menu::checks::option` and clicks an option, the radio button logic doesn't work. This bug was discovered and fixed by nanapro.org forum user "huycan" (I'm just submitting the PR). See this forum thread: http://nanapro.org/en-us/forum/index.php?u=/topic/1256/ggleave-a-menu-open
As mentioned in more detail in the forum thread linked above, my understanding of why this happens is that `menu_builder::checked` fails because the `menu_window` of the submenu is created with the `menu_builder` object used by the parent menu.
> fix: submenu option items unresponsive to clicks

- include/nana/gui/widgets/treebox.hpp
- source/gui/widgets/treebox.cpp
Added new interaction/display mode to treebox control.
Enabling use_entire_line the entire line of the treebox/child is used for mouse interactions and display purposes.
> added treebox use_entire_line mode

- include/nana/gui/animation.hpp
- source/gui/animation.cpp
I noticed some old code still using explicit new/delete. They were trivial to replace with unique_ptr so I went ahead and did it. I think this code is more robust in the presence of exceptions.
I think in operator= swapping is good enough, can't think of any advantage offered by using a new temporary object instead.
> Replace some naked pointers with unique_ptr.

- include/nana/gui/basis.hpp
Need to initialise everything to make sure classes are usable in a constexpr context.
This is useful for my helper `make_accel_key()` function which I will share shortly.
> Initialise everything to make sure accel_key is constexpr.

- source/gui/widgets/skeletons/text_editor.cpp
When you use double-click selection in text editor with non-ascii text, you'll get this assertion
simple fix is to use iswalnum, alongside with already used iswspace.
> Use iswalnum in text editor

- include/nana/paint/graphics.hpp
- source/gui/widgets/toolbar.cpp
- source/paint/graphics.cpp
Ciao,
I modified the way toolbar draw the icons of disabled items.
What I didn't like was the gray square around the disabled icons even if the icons had transparent pixels.
Basically I modified the graphics::rgb_to_wb function adding a flag to skip the transparent pixels of the icons.
Here the result:
For sure there are better way to implement this behavior... I chose the easier without digging to deep into graphic/image code.
> modified toolbar disabled icons drawing

- include/nana/gui/widgets/float_listbox.hpp
- include/nana/gui/widgets/toolbar.hpp
- include/nana/paint/graphics.hpp
- source/gui/widgets/float_listbox.cpp
- source/gui/widgets/toolbar.cpp
- source/paint/graphics.cpp
Hi,
I worked a little on the toolbar here a brief list of changes:
- redesigned toolbar interface
- added dropdown tool
More in detail:
1) added a new version of the append member functions where the first parameter is the tool-type and the last (optional) the event handler. The event is raised when the tool is clicked. The old append member functions are marked as deprecated.
2) added tools_height. This is a replacement for the scale function marked as deprecated. The new name seems "more clear" to me.
3) added append_separator. This is a replacement for the separate function marked as deprecated. Same as before.
4) added count to gets the number of tools and separators.
5) added at(index) to access the tool at specified position.
6) marked as deprecated some of the member functions I …
> Hotfix 1.7.4 new toolbar interface

- source/system/platform.cpp
I tried building nana library on my mac using cmake.
While I was working on it, the output said some necessary header was not included.
So I included the header file and now I can get libnana.a
> Fix : Cmake build error on macOS

- source/gui/widgets/toolbar.cpp
Removed resize event from toolbar to avoid the control is automatically resized when parent is resized   (issue #563)
> Removed resize event from toolbar

- include/nana/gui/notifier.hpp
- source/gui/notifier.cpp
I thought it would be nicer if a user can register multiple tray icon animations.
At first, I tried to give `period` function a new name such as `start_animation`.
Then I realized this is a minor version update, which has to ensure the backward compatibility.
So I modified some of the codes and added some new functions in a way that it won't cause a side effect.
> added a feature : registering multiple tray icon animations

- source/gui/widgets/combox.cpp
This commit solves three combox rendering issues:
1. if one or more list items has an image, and the combox is editable, the background of the image area to the left of the text editor isn't drawn (resulting in a black background area to the left of the text)
2. if one or more list items has an image, the image is not centered vertically when drawn to the left of the text editor
3. if the combox is not editable, the background of text editor area uses predefined constants for the color gradient, ignoring the widget's scheme bgcolor
> fix combox rendering issues

- source/system/split_string.cpp
Hi,
This is a quick fix for #585. It removes the syntax error, when building using Visual Studio, by replacing `and` keyword with `&&` in one of the conditions.
> Fix syntax error when building with VS 2019

- .clang-format
Nana's current coding style is very inconsistent. This patch uses clang-format to format the entire code base.
I choose to apply Webkit's coding style because it's also indenting using 4 spaces. We can discuss what works better.
> apply Webkit coding style

- include/nana/gui/programming_interface.hpp
The code to `enable/disable` the double click event for a widget already existed in [source/gui/programming_interface.cpp](https://github.com/cnjinhao/nana/blob/develop-1.8/source/gui/programming_interface.cpp#L609-L614) but it seems that it was missed out in `include/nana/gui/programming_interface.hpp`, so I have added it.
This now allows us to call `api::enable_double_click(window wd, bool dbl);`
Which is useful if you want to be able to rapidly click on a button and have every click emit a click event, rather than every other click.
> Added ability to call api::enable_double_click

- include/nana/gui/widgets/progress.hpp
- source/gui/widgets/progress.cpp
Please take a look.
I believe the borderless behavior required a simple fix, so I think it should be ok as-is.
Let me know what you think about the second commit, [d88193a](https://github.com/cnjinhao/nana/commit/d88193a765ba909fdbf6f4388a56fee2f9286f01). It adds a struct containing four sides of the widget to color. Maybe a solution similar to this would be an interesting fit for other widgets as well, but I'd really like to hear what you think about this design first.
My IDE had also screwed the indentation, so I sent a third commit to fix it.
Finally, I also renamed the scheme elements as discussed in the issue.
Fixes #604
> Fixed nana::progress borderless bug. Also implemented a border_color struct in the scheme.

- source/gui/widgets/checkbox.cpp
> fix checkbox square misaligned with text

- source/gui/widgets/spinbox.cpp
Changed behavior of double-click event in spinbox control.
BEFORE: double-click was the same of click
NOW: double-click select all the number (or text) inside the spinbox
> Now double click in spinbox select all the number (or text)

- include/nana/gui/detail/window_manager.hpp
- include/nana/gui/programming_interface.hpp
- source/gui/detail/window_manager.cpp
- source/gui/programming_interface.cpp
- source/gui/widgets/button.cpp
- source/gui/widgets/spinbox.cpp
- source/gui/widgets/textbox.cpp
There are widgets that always use tabstop feature (such as `button`, `textbox`, `spinbox`), because it is set at their creation time.
I think it is likely that someone might want to disable the tabstop feature for some widgets.
I got the idea from `eat_tabstop` api and changed `tabstop` function somewhat similar to that.
If nana library has already provided an api that does the same thing, please let me know.
(I'll use that instead and close this pull request)
> added a feature : disabling tabstop

- include/nana/gui/widgets/label.hpp
- source/gui/widgets/label.cpp
Borders can now be added to labels.
Added functions:
- `label::set_border(label::border)`
- `label::add_border(label::border::flag)`
- `label::remove_border(label::border::flag)`
- `label::border_width(unsigned int)`
- `label::border_color(nana::color)`
Example 1
```C++
label lb{ fm };
label::border b{ label::border::all, 1, nana::color(255, 255, 255) };
lb.set_border(b);
```
Example 2
```C++
label lb{ fm };
lb.add_border(label::border::left);
lb.border_width(2);
lb.border_color({ 0, 0, 255 });
```
> Added label borders

- source/gui/widgets/group.cpp
`label::measure` returns a DPI-correct size, so the "px" unit must be used in the div text, otherwise `place` overcompensates for the high DPI, giving the label a size larger than the actual size of the text.
> fix oversized group caption in high DPI mode

- source/gui/element.cpp
Recently, I found out that the implementation for the arrowhead style was missing. 
So I added it (only for the east direction).
Now users can use `arrowhead` submenu arrow style.
> arrowhead direction::east implementation

- include/nana/gui/widgets/listbox.hpp
Currently, the color of the item selection border, and the category foreground color are hard-coded, limiting the ways in which the listbox appearance can be changed (for example, a dark background can't be used). This PR solves the issue by making those colors modifiable by the user.
> listbox scheme additions (item border & category)

- include/nana/pat/cloneable.hpp
- source/charset.cpp
- source/detail/platform_abstraction.cpp
Remove std::move from temporary variables
Do not capture unused variable
> Fix warnings in clang

- source/gui/detail/bedrock_posix.cpp
Home and End keys don't work on linux, they do nothing.
Seems like a correct fix
> convert xk_home xk_end correctly

- include/nana/gui/widgets/skeletons/text_editor.hpp
- include/nana/gui/widgets/textbox.hpp
- source/gui/widgets/skeletons/text_editor.cpp
- source/gui/widgets/textbox.cpp
Added a new function to `textbox` and `text_editor` so that the border that is shown when the widget is clicked on can be disabled.
The need for this was discussed in #656.
Example use to disable it:
```cpp
form fm;
textbox tb{ fm };
tb.enable_border_focused(false);
```
The name of the function may need to be changed though, to maybe something like `enable_focused_border_when_clicked`, so it's more clear.
> textbox focused border can now be disabled

- source/paint/image.cpp
Currently on the Windows platform, window icons must either be a .ico file, a ICO encoded buffer or a resource icon.
To me, this doesn't make much sense, as the Win32 API easily supports creating icons on the fly straight from pixel data.
So in this PR I added support for creating icons directly from the pixel data stored in `nana::paint::image`.
The point of this is that now one can easily set any bmp, png or jpeg (provided png and jpeg are enabled, respectively) as icons as well.
On that note I also wanted to say that the pixel buffer can be quite difficult to get pixel data from. Maybe the API could be improved in that regard.
> Added support for setting arbitrary-format icons on Windows

- include/nana/gui/detail/general_events.hpp
- include/nana/gui/widgets/listbox.hpp
Hi, I'm compiling nana with gcc 13.2 (from msys2 on windows) and std=c++23. Using the switch -Werror=return-type I force to errors the warnings of methods not returning a value through all paths (normally allowed for compatibility with C). So I get an error in the method on general_events.hpp :
```
template<typename Function>
event_handle connect_unignorable(Function && fn, bool in_front = false)
```
which had no return statement in the else branch. Honestly I'm not sure if I'm returning a right/meaningful value, but it then compiles and works normally.
I've also fixed a tiny typo.
> return value in all cases

- build/vc2022/nana.vcxproj
- build/vc2022/nana.vcxproj.filters
- include/nana/gui/detail/window_manager.hpp
- include/nana/gui/msgbox.hpp
- include/nana/gui/programming_interface.hpp
- include/nana/gui/widgets/widget.hpp
- include/nana/paint/graphics.hpp
- source/detail/platform_abstraction.cpp
- source/detail/platform_abstraction.hpp
- source/gui/detail/bedrock_windows.cpp
- source/gui/detail/native_window_interface.cpp
- source/gui/detail/window_manager.cpp
- source/gui/msgbox.cpp
- source/gui/place.cpp
- source/gui/place_parts.hpp
- source/gui/programming_interface.cpp
- source/gui/screen.cpp
- source/gui/widgets/widget.cpp
- source/paint/graphics.cpp
- source/system/platform.cpp
**`source/gui/detail/native_window_interface.cpp`**  **
**`source/detail/platform_abstraction.hpp`**
**`source/detail/platform_abstraction.cpp`** ** (implements dpi_scale, etc. based on SystemParametersInfo, native_window_interface )
**`source/gui/detail/bedrock_windows.cpp`** (responds to WM_DPICHANGED with wd_manager.update_dpi(msgwnd) to update SetWindowPos of root_window )
**`include/nana/paint/graphics.hpp`**
**`source/paint/graphics.cpp`**   ** (uses: platform_abstraction)
`include/nana/gui/detail/window_manager.hpp` (not really)
`source/gui/detail/window_manager.cpp` (uses native_interface::, graphics)
`include/nana/gui/programming_interface.hpp` (not really, but part of API)
`source/gui/programming_interface.cpp ` (uses platform_abstraction::, graphics; interface_type::window_dp) …
> marks dpi todo in Develop 1.8

- include/nana/config.hpp
- include/nana/gui/detail/native_window_interface.hpp
- source/gui/detail/bedrock_windows.cpp
- source/gui/detail/native_window_interface.cpp
- source/gui/programming_interface.cpp
Unfortunately, inputbox and listbox are not usable with 200% or more. 
We better default now to DPI unaware, and I will continue to try to fix it "approximately", but in an experimental branch, to revert the default to DPI aware. 
A real, definitive fix will be very complex...
> Dev dpi make DPI experimental
