cnjinhao/nana

build/cmake/CMakeLists.txt
Hi! I like modern c++ style of nana. I append CMake configuration file for more portable building.
=> Add CMake configuration

CMakeLists.txt, build/cmake/config.hpp
- Disable annoying VS warnings
- Option to enable multiprocessor build on VS
- Move all options to CMake:
- Unicode
- Platform specs
=> CMake improvements

include/nana/gui/detail/general_events.hpp
Hi,
two Q:
arg_dropfiles could be derived from arg_mouse ?
It is possible to have something like: struct arg_drop:arg_mouse {any data;}; ?
=> events doxy comments

include/nana/basic_types.hpp, source/gui/widgets/listbox.cpp
=> fix a few minor inconsistencies in item listbox drawing

source/gui/widgets/checkbox.cpp, source/gui/widgets/listbox.cpp
=> Hotfixes 1.0.1

source/basic_types.cpp
Hi,
How are you?
You were in the right direction.
This will probably fix other errors. 
Now is OK with the secondary monitor.
=> fix wrong positions of menu and tooltip in secondary monitor

.gitignore, CMakeLists.txt, README.md, bii/layout.bii, bii/policies.bii, bii/settings.bii, biicode.conf, include/nana/deploy.hpp, include/nana/std_thread.hpp, source/deploy.cpp, source/detail/platform_spec_selector.cpp
1. The code failed to compile in mingw. I fixed it.
2. Add [biicode](https://www.biicode.com/) support.
=> fix mingw compilation error

include/nana/system/dataexch.hpp, source/system/dataexch.cpp
Hi, I pushed code to set bitmap into clipboard. 
It only supports Windows platform though.
=> add nana::system::dataexch::set(const nana::paint::graphics& g) method

include/nana/gui/widgets/listbox.hpp, source/gui/widgets/listbox.cpp
There are some cases I want to disable sorting feature of listbox.
=> add methods to get/set sortability of listbox

include/nana/gui/basis.hpp, include/nana/gui/widgets/listbox.hpp, include/nana/key_type.hpp, source/gui/widgets/listbox.cpp
From https://github.com/beru/nana/issues/12#issuecomment-95764619
Sorry, I cant test in Linux.
=> FIX / FEATURE: Listbox Export/copy CSV-like; handle Home, End. OK in windows.

CMakeLists.txt
=> Fix Visual Studio 2015 codecvt linker errors

.gitignore, CMakeLists.txt, include/nana/config.hpp, include/nana/deploy.hpp, include/nana/detail/macos_X11/msg_packet.hpp, include/nana/detail/macos_X11/platform_spec.hpp, include/nana/filesystem/file_iterator.hpp, include/nana/filesystem/filesystem.hpp, include/nana/gui/detail/basic_window.hpp, source/charset.cpp, source/deploy.cpp, source/detail/macos_X11/msg_dispatcher.hpp, source/detail/macos_X11/platform_spec.cpp, source/detail/platform_spec_selector.cpp, source/filesystem/file_iterator.cpp, source/filesystem/filesystem.cpp, source/filesystem/fs_utility.cpp, source/gui/detail/bedrock_selector.cpp, source/gui/detail/window_manager.cpp, source/gui/filebox.cpp, source/gui/notifier.cpp, source/gui/timer.cpp, source/gui/widgets/listbox.cpp, source/paint/graphics.cpp, source/system/platform.cpp, source/system/shared_wrapper.cpp, source/system/timepiece.cpp, source/threads/pool.cpp
Hi,
this is a Mac OS X compatible version of Nana. I added some configuration directives to make it work.
Please tell me if it's okay for you.
Benjamin
=> Mac OS X support

include/nana/gui/widgets/listbox.hpp, source/gui/widgets/listbox.cpp
Adds a new event in listbox to notify when the user double-clicks an item.
=> Adding double click event on items, allows block expansion

source/paint/image.cpp
As discussed [here](http://chat.stackoverflow.com/transcript/message/28394446#28394446)
=> Fix different exception specifiers in image.cpp

.travis.yml, README.md
As discussed [here](http://chat.stackoverflow.com/transcript/message/28394615#28394615).
Also adds a TravisCI build badge to the README.
How to activate:
* Before merging the PR:
- go to https://travis-ci.org,
- log in (if necessary),
- click your name and avatar in the top-right corner,
- check (click on, so it turns from grey to green) `cnjinhao/nana`,
- click on the little gear icon, which will take you to the settings page,
- check the option in the top-left corner ("Build only if .travis.yml is present").
* Merge the PR.
Now, each time a commit is pushed to a branch containing a `.travis.yml` file, a build will start and, if it fails, responsible individuals will be notified via e-mail.
Also, if a PR is opened (and is auto-mergable), a build will start targeting the merged state.
=> Add TravisCI support

CMakeLists.txt, README.md, build/vc2015/nana.vcxproj, build/vc2015/nana.vcxproj.filters, include/nana/filesystem/filesystem.hpp, include/nana/filesystem/filesystem_ext.hpp, include/nana/filesystem/filesystem_selector.hpp, source/filesystem/filesystem.cpp
Hi,
I think that to have all the demos direct in CI (continuous integration) in windows and Linux is very convenient.
Once a hotfix pass all "test" (inclusive demos) it can be merged in master, creating a new path version.
like 1.3.01 . This can be then merge into develop branch. So develop will be not to hard to merge back to master once it is OK, and bugs will be corrected. Maybe it is best to have hotfix branch without version in the name - this is convenient for use in automation. For example if I have automation in my project or in nana-demo I can use hotfix, and not master, but if it change with number version it will not work . So, any version will be only a Tag (and not a branch) in GitHub, that will not change and can not brake.
I will add more tests, more configurations and …
=> most demos OK in CI travis

.travis.yml, CMakeLists.txt, README.md, build/vc2015/nana.vcxproj, build/vc2015/nana.vcxproj.filters, include/nana/filesystem/filesystem.hpp, include/nana/filesystem/filesystem_ext.hpp, include/nana/filesystem/filesystem_selector.hpp, source/filesystem/filesystem.cpp
Hi,
this is a final version of #112 . You can first merge that and then merge this. Or just merge this, as you wish.
You may prefer to merge it into a new develop branch that come from hotfix to test first...
=> Filesystem

.travis.yml, source/gui/widgets/listbox.cpp
A very simple but effective improvement
=> 3 instead of 1 step by list wheel scroll

include/nana/gui/widgets/listbox.hpp, source/gui/widgets/listbox.cpp
Fix a drawing defect
Also, note some reversible changes in the geometry of the list scheme (header 20 not 24, etc.)
=> FIX a drawing defect and use Geometric scheme

.travis.yml, include/nana/c++defines.hpp, include/nana/filesystem/filesystem.hpp, include/nana/filesystem/filesystem_ext.hpp, include/nana/filesystem/filesystem_selector.hpp, include/nana/gui/filebox.hpp, include/nana/paint/detail/image_impl_interface.hpp, include/nana/paint/graphics.hpp, source/filesystem/filesystem.cpp, source/gui/filebox.cpp, source/paint/detail/image_bmp.hpp, source/paint/detail/image_ico.hpp, source/paint/detail/image_jpeg.hpp, source/paint/image.cpp
more consistent use of the versions of the filesystem to make the linker happy. 
It also prepare us for the std::filesystem (no experimental).
I will need to separate the cmake  of the demos...
=> Dev nana fs

.travis.yml, CMakeLists.txt, include/nana/gui/detail/window_manager.hpp
as promised in  #138  the branches in nana-demo will have the same name
=> cleaning Develop

include/nana/gui/place.hpp, source/gui/place.cpp
Note: I reverted the previous commit because it had an incorrect formatting.
=> place::modify() now correctly updates the text to place::div_text.

source/gui/notifier.cpp, source/paint/detail/image_ico_ex.hpp, source/paint/image.cpp
**Note:** I haven't tried all the possible scenarios, please test it before merging.
=> Added multi platform support for ICOns files.

.travis.yml
and  master with master, and develop with develop.
=> travi test nana/hotfix with nana-demo/hotfix

.travis.yml
clone branch=hotfix-1.5 qPCR4vir/nana-demo
=> update link to v1.5 in demos

build/codeblocks/nana.cbp, build/codeblocks/nana.depend
So that it will build 'out of the box'.  Set c++11.  Define
enable_std_make_unique.  Define various _WIN32*   Add boost library to
search folders.
=> Fix codeblocks build project

build/vc2017/nana.vcxproj, build/vc2017/nana.vcxproj.filters, source/gui/place.cpp
Hi,
I was thinking in an easy way to improve the readability of the place div-string and I think that if we use `width `and `height `instead of `weight` it will be much more easy to see where we are, in what direction.
Compare:
```
vertical   gap=2                                    
<height=25>                             
<height=25  OpenSave>                   
<textBox>                               
<height=25 <width=15>                  
<re width=50 gap=2>         
<panic width=50>            
< >                          
<def  gap=2 width=120>      
< >                          
<hide width=50>             
<width=15> >                
<height=5>       
```                
and 
```
vertical   gap=2                                    
<weight=25> …
```
=> improve the readability of the place div-string by using width and height instead of weight

.gitignore, .travis.yml, CMakeLists.txt, build/vc2015/nana.vcxproj, build/vc2015/nana.vcxproj.filters, build/vc2017/nana.vcxproj, include/nana/c++defines.hpp, include/nana/gui/widgets/detail/tree_cont.hpp, include/nana/gui/widgets/treebox.hpp, source/gui/widgets/treebox.cpp
Hi,
sorry, here are all my actualization to Hotfix 1.5.5. Select what you want. This are minor configurations changes and a few comments.
It apparently solved some problems with CLion - MinGW, etc. It partially adreeses #269
=> actualizations to Hotfix 1.5.5

include/nana/gui/widgets/tabbar.hpp
I also provided the same change as  #285 to the hotfix, that I requested for develop.
=> Added missing std::move [Hotfix Branch]

include/nana/gui/widgets/toolbar.hpp, source/gui/widgets/toolbar.cpp
I am sorry, git diff is drunk :(
toolbar.hpp line 36-42 changed and 99-100
toolbar.cpp line 424-427.
I added a struct that allows you to disable a toolbar item right after appending it.
=> Feature toolbar proxy

include/nana/gui/widgets/listbox.hpp, include/nana/gui/widgets/menubar.hpp, source/gui/widgets/listbox.cpp, source/gui/widgets/menubar.cpp
Added listbox::clear_headers() to remove all the columns from the listbox
Added menubar::clear() to remove all the items from menubar
=> Added listbox::clear_headers() and menubar::clear()

include/nana/gui/widgets/group.hpp, include/nana/gui/widgets/toolbar.hpp, source/gui/widgets/group.cpp, source/gui/widgets/toolbar.cpp
Added group.field_display() and group.erase() 
Added toolbar.clear()
=> Added group.field_display() , group.erase()  and toolbar.clear() 

include/nana/gui/widgets/tabbar.hpp, source/gui/filebox.cpp, source/gui/widgets/tabbar.cpp
=> fix folderbox init_path

include/nana/gui/widgets/tabbar.hpp, source/gui/widgets/tabbar.cpp
tab_click event is processed when a tab is clicked
=> Added tab_click event to tabbar control

include/nana/gui/widgets/detail/tree_cont.hpp
replace https://github.com/cnjinhao/nana/pull/350
see picture there
=> FIX crash while deleting a selected tree node

source/gui/widgets/slider.cpp
Fix suggested be Error Flynn in http://nanapro.org/en-us/forum/index.php?u=/topic/1059/ggslider-appearance-when-disabled#post-2498
=> Prevent slider adorn moving when slider disabled

include/nana/gui/widgets/listbox.hpp, source/gui/widgets/listbox.cpp
I need to reorder a range of columns based on the values in some row. 
This is a possible implementation for that "feature".
It is working, but,  of course review it carefully.
=> Resort column range

.travis.yml, include/nana/filesystem/filesystem.hpp, source/filesystem/filesystem.cpp, source/gui/filebox.cpp
After debugging, it resolved my problem in: https://github.com/cnjinhao/nana/issues/408
=> fix crash by using empty path to initialize folderbox with fs canonical() which don't exist

include/nana/gui/detail/drawer.hpp, include/nana/gui/detail/event_code.hpp, include/nana/gui/layout_utility.hpp, include/nana/gui/msgbox.hpp, include/nana/gui/programming_interface.hpp, include/nana/gui/widgets/date_chooser.hpp, include/nana/gui/widgets/form.hpp, include/nana/gui/widgets/group.hpp, include/nana/gui/widgets/menubar.hpp, include/nana/gui/widgets/panel.hpp, include/nana/gui/widgets/picture.hpp, include/nana/gui/widgets/scroll.hpp, include/nana/gui/widgets/spinbox.hpp, source/gui/detail/drawer.cpp, source/gui/layout_utility.cpp, source/gui/widgets/group.cpp, source/paint/graphics.cpp
Hi, this PR corrects a misspelling.
=> Fix wrongly spelt words

.travis.yml, build/cmake/compilers.cmake, build/cmake/verbose.cmake, build/vc2017/nana.vcxproj, build/vc2017/nana.vcxproj.filters, include/nana/gui/dragdrop.hpp, include/nana/gui/place.hpp, include/nana/gui/widgets/group.hpp, include/nana/gui/widgets/listbox.hpp, include/nana/gui/widgets/spinbox.hpp, include/nana/gui/widgets/treebox.hpp, source/gui/place.cpp, source/gui/place_parts.hpp, source/gui/widgets/categorize.cpp, source/gui/widgets/group.cpp, source/gui/widgets/listbox.cpp
a cleaner PR, replace #426. Still to continue and documenting, but working.
=> Test error

source/gui/place_parts.hpp, source/gui/widgets/toolbar.cpp
fixed bug in dock_pane caption drawing function (used a workaround that hide the caption when the dock_pane width become too small)
fixed small bug in toolbar
=> dock_pane and toolbar bug fix

include/nana/gui/widgets/listbox.hpp, source/gui/widgets/listbox.cpp
…width=0
(cherry picked from commit 23efa5088d742a48e7ad07f273e84bcf50c2d979)
=> new feature "fit_width_to_header caption text" for a new header with width=0

.travis.yml, CMakeLists.txt, build/cmake/select_filesystem.cmake, include/nana/filesystem/filesystem.hpp, include/nana/filesystem/filesystem_ext.hpp, source/filesystem/filesystem.cpp, source/gui/filebox.cpp, source/gui/msgbox.cpp
This need more testing !!
See:
http://nanapro.org/en-us/forum/index.php?u=/topic/1237/ggunable-to-build-nana-when-selected-boost-filesystem
=> Filesystem build simplification

README.md, include/nana/c++defines.hpp, include/nana/filesystem/filesystem.hpp, include/nana/filesystem/filesystem_ext.hpp, source/filesystem/filesystem.cpp
in preparation to possible release 1.7.3
and please merge hotfix back into develop, so I can update that too. Thank!
=> Some comments and minor fixes

.travis.yml, CMakeLists.txt, build/cmake/select_filesystem.cmake, build/cmake/shared_libs.cmake, include/nana/gui/programming_interface.hpp, include/nana/gui/widgets/button.hpp, include/nana/gui/widgets/form.hpp, source/gui/widgets/form.cpp, source/gui/widgets/listbox.cpp, source/paint/image.cpp
This will FIX travis broken by #469, #492
Run-test one more demo: helloworld_demo
Improve performance of listbox
Run all test
=>  FIX travis 

build/cmake/select_filesystem.cmake
Hi, I'd like to have this one in develop-1.8 branch.
Otherwise, I won't be able to build the library with VS2019 it seems.
#513 is related.
=> CMake command check_include_file_cxx (from develop branch)

source/system/split_string.cpp
- Causes compiler errors on MSVC
=> Change keyword ``and`` to ``&&``

source/audio/detail/audio_device.cpp
=> Make audio_device.cpp more robust

source/gui/widgets/button.cpp
test code
```cpp
btn.transparent(true).edge_effects(false).enable_focus_color(false).borderless(true);
btn.transparent(true).edge_effects(false).enable_focus_color(false).borderless(false);
```
=> Fixed a problem that borderless was not applied to buttons

source/gui/detail/bedrock_windows.cpp
Fix : nested form can't get mouse wheel event.
=> fix mouse wheel on nested form

.devcontainer/Dockerfile, .devcontainer/Dockerfile.alpine, .devcontainer/devcontainer.json
=> Add devcontainer

source/detail/platform_spec_posix.cpp
=> Fix warning in gcc 10

include/nana/gui/widgets/date_chooser.hpp, source/gui/widgets/date_chooser.cpp, source/gui/widgets/label.cpp
=> Fix warnings

source/paint/pixel_buffer.cpp
Fixes #664.
@cnjinhao please merge this as this branch cannot be built under MSVC right now.
=> Fixed int conversions in pixel_buffer::ellipse.

include/nana/gui/widgets/combox.hpp, include/nana/gui/widgets/treebox.hpp, source/gui/widgets/skeletons/text_editor.cpp
Just a fix for compiler warnings.
=> fix compiler warnings

.gitignore, appveyor.yml, build/vc2022/nana.sln, build/vc2022/nana.vcxproj, build/vc2022/nana.vcxproj.filters, include/nana/gui/widgets/listbox.hpp
Minor changes, compiled with PlatformToolset v143
All demos working. Not tested every feature.
=> test nana-demo with VS2022 preview 17.9

build/vc2019/nana.sln, build/vc2019/nana.vcxproj, build/vc2022/nana.sln, build/vc2022/nana.vcxproj
Visual Studio 2019 supoorts ARM, ARM64, ARM64EC.
=> Add arm platforms

source/gui/widgets/menu.cpp
Need to fix draw issues with menu with DPI scaling. This issue was caused by this [commit](https://github.com/cnjinhao/nana/commit/b21c6ec6600060461c7c145bb82e792b4f4edbe9)
Cheers!
=> Fixed menu draw issues with borders and active item

include/nana/gui/widgets/treebox.hpp, source/gui/widgets/treebox.cpp
See https://github.com/cnjinhao/nana/issues/691 for more details.
=> New Treebox multi select feature
